# Generated by Django 5.2.7 on 2026-05-24 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__lte', Decimal('9999.99'))), name='product_price_max'),
        ),
    ]
