# Generated by Django 5.2.7 on 2026-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada'), ('CLEANING', 'Limpiando')], default='FREE', max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='table_number_gte_one'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='table_capacity_gte_one')],
            },
        ),
    ]
