# Generated by Django 5.2.7 on 2026-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('number__lte', 200)), name='table_number_lte_200'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__lte', 50)), name='table_capacity_lte_50'),
        ),
    ]
