# Generated by Django 5.2.7 on 2026-05-24 02:15

import apps.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15, validators=[apps.core.validators.validate_phone])),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('estimated_time_min', models.PositiveIntegerField()),
                ('courier_status', models.CharField(choices=[('ASSIGNED', 'Asignado'), ('ON_ROUTE', 'En camino'), ('DELIVERED', 'Entregado')], default='ASSIGNED', max_length=20)),
            ],
        ),
    ]
