# Generated by Django 5.2.7 on 2026-05-24 02:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km__gte', 0)), name='delivery_distance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km__lte', Decimal('15.00'))), name='delivery_distance_max'),
        ),
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_time_min__gte', 5)), name='delivery_time_min'),
        ),
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_time_min__lte', 180)), name='delivery_time_max'),
        ),
        migrations.AddConstraint(
            model_name='deliveryinfo',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='delivery_fee_non_negative'),
        ),
    ]
