# Generated by Django 5.2.7 on 2026-05-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='courier_status',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Asignado'), ('ON_ROUTE', 'En camino'), ('DELIVERED', 'Entregado')], default='ASSIGNED', max_length=20),
        ),
    ]
