# Generated by Django 5.2.7 on 2026-05-24 02:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Mesa'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dining.table')),
            ],
        ),
    ]
