# Generated by Django 5.2.7 on 2026-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_product_price_max'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', 100)), name='order_item_qty_max'),
        ),
    ]
